import React from "react";
import { AbsoluteFill, Img, interpolate, Sequence, staticFile, useCurrentFrame } from "remotion";

const C = { paper: "#fffaf3", ink: "#191919", muted: "#676767", red: "#e5484d", yellow: "#f7c948", teal: "#75c9c8", green: "#25d366", white: "#fff" };
const products = [
  { name: "Modular storage", image: "modular-dry-storage-set.svg", price: "GH₵950" },
  { name: "Speedy chopper", image: "speedy-chopper.svg", price: "GH₵365" },
  { name: "Eco water bottle", image: "eco-water-bottle.svg", price: "GH₵180" },
];
const smooth = (v: number) => v * v * (3 - 2 * v);

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const frame = useCurrentFrame();
  const progress = smooth(Math.min(1, Math.max(0, (frame - delay) / 18)));
  return <div style={{ opacity: progress, transform: `translateY(${(1 - progress) * 30}px)` }}>{children}</div>;
}
function Scene({ children }: { children: React.ReactNode }) {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 8, 82, 90], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  return <AbsoluteFill style={{ opacity }}>{children}</AbsoluteFill>;
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <div style={{ color: C.red, fontSize: 27, fontWeight: 800, letterSpacing: 4, textTransform: "uppercase" }}>{children}</div>; }
function Heading({ children, size = 72 }: { children: React.ReactNode; size?: number }) { return <div style={{ marginTop: 20, fontFamily: "Georgia, serif", fontSize: size, lineHeight: 0.96, fontWeight: 800 }}>{children}</div>; }
function Phone({ children }: { children: React.ReactNode }) { return <div style={{ width: 650, height: 1080, border: `14px solid ${C.ink}`, borderRadius: 52, backgroundColor: C.white, overflow: "hidden", boxShadow: "0 25px 65px rgba(25,25,25,.2)" }}><div style={{ height: 42, backgroundColor: C.ink }} />{children}</div>; }
function Bar({ label }: { label: string }) { return <div style={{ height: 76, padding: "0 25px", display: "flex", alignItems: "center", gap: 11, backgroundColor: "#f3f0ea", borderBottom: "1px solid #dedbd4", color: C.muted, fontSize: 21 }}><span style={{ color: C.red, fontSize: 30 }}>●</span>{label}</div>; }
function Catalog() { const frame = useCurrentFrame(); const scroll = interpolate(frame, [0, 75], [0, -150], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }); return <Phone><Bar label="abyshub.vercel.app" /><div style={{ padding: "30px 25px", transform: `translateY(${scroll}px)` }}><div style={{ color: C.red, fontSize: 18, fontWeight: 800, letterSpacing: 2 }}>THE SHOP</div><div style={{ marginTop: 10, fontFamily: "Georgia, serif", fontSize: 48, fontWeight: 800 }}>Everything</div><div style={{ marginTop: 20, display: "grid", gap: 15 }}>{products.map((p) => <div key={p.name} style={{ display: "flex", alignItems: "center", gap: 15, padding: 15, backgroundColor: C.paper, border: "1px solid #e7e1d8", borderRadius: 16 }}><div style={{ width: 125, height: 125, backgroundColor: "#f3f0ea", borderRadius: 12, position: "relative" }}><Img src={staticFile(p.image)} style={{ width: "100%", height: "100%", objectFit: "contain" }} /></div><div><div style={{ fontSize: 23, fontWeight: 800 }}>{p.name}</div><div style={{ marginTop: 9, color: C.red, fontSize: 24, fontWeight: 800 }}>{p.price}</div><div style={{ marginTop: 8, color: C.muted, fontSize: 18 }}>Add to basket →</div></div></div>)}</div></div></Phone>; }
function Checkout() { return <Phone><Bar label="abyshub.vercel.app / checkout" /><div style={{ padding: 30 }}><div style={{ color: C.muted, fontSize: 18, letterSpacing: 2, fontWeight: 800 }}>CHECKOUT</div><Heading size={43}>Your basket</Heading><div style={{ marginTop: 23, padding: 20, backgroundColor: C.paper, borderRadius: 16, border: "1px solid #e7e1d8", fontSize: 22 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>Modular storage</span><b>GH₵950</b></div><div style={{ marginTop: 15, height: 1, backgroundColor: "#ddd5c9" }} /><div style={{ marginTop: 15, display: "flex", justifyContent: "space-between", color: C.red }}><b>Total</b><b>GH₵950</b></div></div><div style={{ marginTop: 26, color: C.muted, fontSize: 18, letterSpacing: 2, fontWeight: 800 }}>CUSTOMER DETAILS</div>{["Full name", "Phone number", "Delivery address"].map((label) => <div key={label} style={{ marginTop: 13, padding: "16px 18px", border: "1px solid #d8d2c8", borderRadius: 11, color: C.muted, fontSize: 20 }}>{label}</div>)}<div style={{ marginTop: 22, padding: 18, textAlign: "center", backgroundColor: C.red, color: C.white, borderRadius: 13, fontSize: 22, fontWeight: 800 }}>Continue to payment</div></div></Phone>; }
function Payment() { const success = smooth(Math.min(1, Math.max(0, (useCurrentFrame() - 48) / 18))); return <Phone><Bar label="abyshub.vercel.app / payment" /><div style={{ padding: 30 }}><div style={{ color: C.muted, fontSize: 18, letterSpacing: 2, fontWeight: 800 }}>SECURE PAYMENT</div><Heading size={42}>Choose how to pay</Heading>{[{ label: "Mobile Money", mark: "MOMO", color: C.yellow }, { label: "Debit or credit card", mark: "CARD", color: C.teal }].map((o) => <div key={o.label} style={{ marginTop: 22, padding: 22, display: "flex", alignItems: "center", gap: 17, border: `4px solid ${o.color}`, borderRadius: 16, fontSize: 22, fontWeight: 800 }}><div style={{ width: 72, height: 50, display: "grid", placeItems: "center", backgroundColor: o.color, borderRadius: 9, fontSize: 15 }}>{o.mark}</div>{o.label}</div>)}<div style={{ marginTop: 39, padding: 25, textAlign: "center", borderRadius: 16, backgroundColor: C.green, color: C.white, opacity: success, transform: `scale(${.9 + success * .1})` }}><div style={{ fontSize: 50 }}>✓</div><div style={{ fontSize: 24, fontWeight: 800 }}>Payment successful</div></div></div></Phone>; }
function WhatsApp() { const sent = useCurrentFrame() > 45; return <Phone><div style={{ height: 98, padding: "0 25px", display: "flex", alignItems: "center", gap: 16, backgroundColor: C.green, color: C.white }}><div style={{ width: 52, height: 52, display: "grid", placeItems: "center", borderRadius: "50%", backgroundColor: C.white, color: C.green, fontSize: 30, fontWeight: 800 }}>↗</div><div><div style={{ fontSize: 23, fontWeight: 800 }}>Abys Hub orders</div><div style={{ fontSize: 16 }}>online now</div></div></div><div style={{ padding: 25, backgroundColor: "#e8f7e5", height: 940 }}><div style={{ textAlign: "center", color: C.muted, fontSize: 16 }}>TODAY</div><div style={{ marginTop: 35, padding: 19, maxWidth: 450, backgroundColor: C.white, borderRadius: "16px 16px 16px 4px", fontSize: 21, lineHeight: 1.25 }}>Need a bulk order? Send us what you need and we&apos;ll help.</div>{sent ? <div style={{ marginTop: 22, marginLeft: 85, padding: 19, backgroundColor: "#d5ffc8", borderRadius: "16px 16px 4px 16px", fontSize: 21, lineHeight: 1.25 }}>I&apos;d like 20 storage sets and 15 choppers. ✓✓</div> : null}<div style={{ position: "absolute", left: 42, right: 42, bottom: 28, padding: "18px 21px", backgroundColor: C.white, borderRadius: 30, color: C.muted, fontSize: 21 }}>Bulk Order on WhatsApp</div></div></Phone>; }

export const AbysHubOrderAd: React.FC = () => {
  const frame = useCurrentFrame();
  const pulse = interpolate(frame % 45, [0, 22, 45], [.97, 1.03, .97]);
  return <AbsoluteFill style={{ backgroundColor: C.paper, color: C.ink, fontFamily: "Trebuchet MS, sans-serif", overflow: "hidden" }}><AbsoluteFill style={{ background: "linear-gradient(145deg, #fff0c8, #fffaf3 52%, #d8f4f0)" }} /><div style={{ position: "absolute", width: 850, height: 850, borderRadius: "50%", backgroundColor: C.yellow, opacity: .17, top: -300, right: -280, transform: `scale(${pulse})` }} />
    <Sequence from={0} durationInFrames={100}><Scene><div style={{ padding: "110px 72px", textAlign: "center" }}><Reveal><Img src={staticFile("abys-hub-logo.png")} style={{ width: 260 }} /></Reveal><div style={{ marginTop: 190 }}><Reveal delay={10}><Eyebrow>Now online</Eyebrow><Heading size={90}>Ordering just<br /><span style={{ color: C.red }}>got easier.</span></Heading><div style={{ margin: "30px auto 0", maxWidth: 800, color: C.muted, fontSize: 35, lineHeight: 1.2 }}>We&apos;ve made ordering from us easier than ever!</div></Reveal></div></div></Scene></Sequence>
    <Sequence from={90} durationInFrames={100}><Scene><div style={{ padding: "90px 72px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}><Reveal><Eyebrow>Browse our products</Eyebrow><Heading size={59}>Tupperware and more.</Heading></Reveal><div style={{ marginTop: 30 }}><Catalog /></div></div></Scene></Sequence>
    <Sequence from={180} durationInFrames={100}><Scene><div style={{ padding: "90px 72px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}><Reveal><Eyebrow>Place your order</Eyebrow><Heading size={59}>Simple checkout.</Heading></Reveal><div style={{ marginTop: 30 }}><Checkout /></div></div></Scene></Sequence>
    <Sequence from={270} durationInFrames={100}><Scene><div style={{ padding: "90px 72px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}><Reveal><Eyebrow>Pay securely</Eyebrow><Heading size={59}>Mobile Money<br />or your card.</Heading></Reveal><div style={{ marginTop: 25 }}><Payment /></div></div></Scene></Sequence>
    <Sequence from={360} durationInFrames={100}><Scene><div style={{ padding: "90px 72px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}><Reveal><Eyebrow>Bulk orders</Eyebrow><Heading size={59}>Need to order<br />a lot?</Heading></Reveal><div style={{ marginTop: 25 }}><WhatsApp /></div></div></Scene></Sequence>
    <Sequence from={450} durationInFrames={150}><Scene><div style={{ padding: "200px 72px 0", textAlign: "center" }}><Reveal><Img src={staticFile("abys-hub-logo.png")} style={{ width: 240 }} /><div style={{ marginTop: 135 }}><Eyebrow>Visit our website today</Eyebrow><Heading size={86}>Place your<br /><span style={{ color: C.red }}>order now.</span></Heading><div style={{ margin: "48px auto 0", padding: "23px 32px", width: 680, backgroundColor: C.red, color: C.white, borderRadius: 17, fontSize: 41, fontWeight: 900, letterSpacing: 3, transform: `scale(${interpolate(frame % 36, [0, 18, 36], [.96, 1.04, .96])})` }}>ORDER NOW</div><div style={{ marginTop: 27, fontSize: 35, fontWeight: 800 }}>abyshub.vercel.app</div><div style={{ marginTop: 16, color: C.muted, fontSize: 26 }}>Tupperware and more · Nationwide delivery</div></div></Reveal></div></Scene></Sequence>
  </AbsoluteFill>;
};
